name: Push to GitLab

on:
  push:
    branches:
      - master

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/faruk67/data-pipeline.git
          git fetch origin master
          git push --force gitlab master:main
          

